### PR TITLE
Facilitate compability with oemof-solph v4.0

### LINKED ISSUE #32: oemof version needs to be updated from v0.2.2 to v0.4
Update old oemof version to newer one. ensure compatability, ie. some parameters will have to be renamed.

### PR DESCRIPTION
**Pull request by smartie2076**
Fix #32

### CODE REVIEW

**Comment by smartie2076** [comment]
Left to do before merging: Check that outputs with oemof==0.2.2 is the same as with oemof-solph==0.4.0.

**Comment by smartie2076** [comment]
Update to pyomo==5.7!

**Comment by smartie2076** [comment]
@santiagoinfantinom I did some major updates, also regarding the oemof version used. Please uninstall oemof and install the new requirements. Update your banches ASAP, as there are many changes. I will probably will create another release soon.

**Comment by santiagoinfantinom** [comment]
@smartie2076 Ok. I'm going to uninstall oemof and reinstall the requirements. After that i'll merge dev into the other branches

**Pull request merged**
