### PR TITLE
Fixing readthedocs

### LINKED ISSUE #41: Wiki needs to be moved to readthedocs
This would then include a version control system.

### LINKED ISSUE #49: [Bug] Readthedocs is not working
The readthedocs is not working. Please use [this](https://github.com/rl-institut/mvs_eland/tree/dev/docs) as a reference on what might be wrong - basically, the structure should be the same in Offgridders.

### PR DESCRIPTION
**Pull request by santiagoinfantinom**
Fix #41  
Fix #49

### CODE REVIEW

**Comment by santiagoinfantinom** [comment]
So war das gemeint oder? :)

**Comment by Bachibouzouk** [comment]
Hello Santiago, you can ping @smartie2076 by using the github handle with @ in front ;)

**Comment by smartie2076** [comment]
Hi @santiagoinfantinom , I have now added you to the readthedocs.io account of Offgridders - not sure if you can log in there now. There where some settings that I changed here (https://readthedocs.org/dashboard/offgridders/advanced/), and I copied the yml file from the MVS and now the document compiles.

**Comment by smartie2076** [comment]
This PR is ready to merge as soon as #56 is solved and the travis tests run through.

**Pull request merged**
