### PR TITLE
Fix/model structure

### PR DESCRIPTION
**Pull request by santiagoinfantinom**
Draft pull request for changing the structure from class2functions

### CODE REVIEW

**Comment by santiagoinfantinom** [comment]
I don't know what happend here. I force-pushed directly from PyCharm and this PR got close. What might have happened?

**Comment by Bachibouzouk** [comment]
I usually work on git in a separate terminal , so I don't really know what might have happened

**Comment by Bachibouzouk** [comment]
I think you merged this branch into dev locally

**Comment by Bachibouzouk** [comment]
the branch `fix/model_structure` seems to still be buggy, so I moved the commits merged in dev by accident into #68

**Pull request closed without merging**
